title: Ranjan Marathe blog
email: FirstName.LastName@gmail.com
description: >-
  Musings of a life long learner.
baseurl: "/marathe"
url: ""
twitter_username: 6C1_16
github_username: priyaranjanmarathe

collections:
  til:
    output: true
    permalink: /til/:title/

theme: minima
plugins:
  - jekyll-feed

disqus:
  shortname: priyaranjanmarathe
