title: Ranjan Marathe blog
email: FirstName.LastName@gmail.com
description: >-
  Musings of a life long learner.
baseurl: ""
url: ""
bluesky: priyaranjan.bsky.social
github_username: priyaranjanmarathe
twitter_username: 6C1_16

collections:
  til:
    output: true
    permalink: /til/:title/
  bot:
    output: true
    permalink: /bot/:title/

# theme: minima
remote_theme: jekyll/minima

plugins:
  - jekyll-feed

disqus:
  shortname: priyaranjanmarathe
